-- https://school.programmers.co.kr/learn/courses/30/lessons/301647

WITH CTE AS(
    SELECT ID, GENOTYPE
    FROM ECOLI_DATA
)

SELECT E.ID, E.GENOTYPE, C.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA E
    JOIN CTE C
    ON E.PARENT_ID = C.ID
WHERE (E.GENOTYPE & C.GENOTYPE) = C.GENOTYPE
ORDER BY E.ID