-- https://school.programmers.co.kr/learn/courses/30/lessons/301649

-- 코드를 작성해주세요
WITH RANKED_CTE AS (
    SELECT
        ID,
        SIZE_OF_COLONY,
        ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY DESC) AS ROW_NUM,
        COUNT(*) OVER() AS TOTAL_COUNT
    FROM ECOLI_DATA
)

SELECT ID, CASE
    WHEN ROW_NUM <= TOTAL_COUNT*0.25 THEN 'CRITICAL'
    WHEN ROW_NUM <= TOTAL_COUNT*0.5 THEN 'HIGH'
    WHEN ROW_NUM <= TOTAL_COUNT*0.75 THEN 'MEDIUM'
    ELSE 'LOW' END AS COLONY_NAME
FROM RANKED_CTE
ORDER BY ID