-- https://school.programmers.co.kr/learn/courses/30/lessons/144855

SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK_SALES S
    JOIN BOOK B
    ON S.BOOK_ID = B.BOOK_ID
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY CATEGORY
ORDER BY 1