-- https://school.programmers.co.kr/learn/courses/30/lessons/157340

SELECT CAR_ID, CASE WHEN
    SUM('2022-10-16' BETWEEN START_DATE AND END_DATE) < 1 THEN '대여 가능'
    ELSE '대여중'
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY 1
ORDER BY 1 DESC

# SELECT CAR_ID,
# CASE
#     WHEN COUNT(CASE WHEN '2022-10-16' BETWEEN START_DATE AND END_DATE THEN 1 END) > 0 THEN '대여중'
#     ELSE '대여 가능' END AS AVAILABILITY
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# GROUP BY CAR_ID
# ORDER BY 1 DESC