-- https://school.programmers.co.kr/learn/courses/30/lessons/59042

SELECT ANIMAL_ID, NAME
FROM ANIMAL_OUTS
WHERE ANIMAL_ID NOT IN (
    SELECT ANIMAL_ID
    FROM ANIMAL_INS
)
ORDER BY 1,2


# SELECT O.ANIMAL_ID, O.NAME
# FROM ANIMAL_OUTS O
# LEFT JOIN ANIMAL_INS I
# ON I.ANIMAL_ID = O.ANIMAL_ID
# WHERE I.ANIMAL_ID IS NULL
# ORDER BY O.ANIMAL_ID


# -- 코드를 입력하세요
# SELECT O.ANIMAL_ID, O.NAME
# FROM ANIMAL_INS I
#     RIGHT JOIN ANIMAL_OUTS O
#     ON I.ANIMAL_ID = O.ANIMAL_ID
# WHERE I.ANIMAL_ID IS NULL
# # ORDER BY O.ANIMAL_ID, O.NAME