-- https://school.programmers.co.kr/learn/courses/30/lessons/299305

SELECT A.ID,
       SUM(CASE WHEN B.ID IS NOT NULL THEN 1 ELSE 0 END) AS CHILD_COUNT
FROM ECOLI_DATA A
LEFT JOIN ECOLI_DATA B ON A.ID = B.PARENT_ID
GROUP BY A.ID
ORDER BY A.ID

# -- 코드를 작성해주세요
# SELECT A.ID, COUNT(B.PARENT_ID) AS CHILD_COUNT
# FROM ECOLI_DATA A
# LEFT JOIN ECOLI_DATA B
# ON A.ID = B.PARENT_ID
# GROUP BY A.ID
# ORDER BY A.ID