-- https://school.programmers.co.kr/learn/courses/30/lessons/301651

WITH RECURSIVE ECOLI_TREE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT ED.ID, ED.PARENT_ID, ET.GENERATION + 1
    FROM ECOLI_DATA ED
    JOIN ECOLI_TREE ET ON ED.PARENT_ID = ET.ID
)

SELECT COUNT(*) AS `COUNT`, GENERATION
FROM ECOLI_TREE ET
LEFT JOIN ECOLI_DATA ED ON ET.ID = ED.PARENT_ID
WHERE ED.ID IS NULL
GROUP BY GENERATION
ORDER BY GENERATION