-- https://school.programmers.co.kr/learn/courses/30/lessons/131534

SELECT DATE_FORMAT(O.SALES_DATE, '%Y') AS YEAR,
        DATE_FORMAT(O.SALES_DATE, '%m') AS MONTH,
        COUNT(DISTINCT U.USER_ID) AS PURCHASED_USERS,
        ROUND(COUNT(DISTINCT U.USER_ID)/( SELECT COUNT(DISTINCT USER_ID)
            FROM USER_INFO U
            WHERE JOINED LIKE '2021%'), 1) as PUCHASED_RATIO
FROM USER_INFO U
    JOIN ONLINE_SALE O
    ON U.USER_ID = O.USER_ID
WHERE JOINED LIKE '2021%'
GROUP BY YEAR, MONTH